version: '3'

services:
  loadbalancer:
    #image: nginx:latest
    build:
      context: .
    ports:
     - 8000:8000
     - 8001:8001
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - cache:/var/cache/nginx
    networks:
     - net
  echo:
    image: fl64/echo-http:latest
    networks:
     - net

volumes:
  cache:

networks:
  net:
